version: '3'
services:
  app:
    build: .
    entrypoint: ["/app/docker/entrypoint.sh"]
    command: bundle exec foreman start
    command: /bin/bash -c "while true; do sleep 10; done"
    volumes:
      - .:/app
      - gems:/gems
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3035:3035"
    depends_on:
      - db
    stdin_open: true
    # Allows us to send signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    #docker-compose run --service-ports app (ao inves de docker-compose up para debugging)

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
  gems: